In [1]:
import numpy as np

from metrics import dist_cov, dist_cov_, dist_var, dist_var_

In [2]:
t1 = np.zeros((20, 30, 10))
t2 = np.zeros((20, 30, 10))
assert dist_cov(t1, t2) == 0
assert dist_var(t1) == 0

In [3]:
# very slow but as easy as it gets
# we imply rbf kernel with gamma=1
def unit_test_var(tensor):
    n, m, _ = tensor.shape
    n_inner = 0
    n_outer = 0
    inner = 0
    outer = 0
    for i in range(n):
        for j in range(m):
            for s in range(n):
                for t in range(m):
                    # within clusters
                    if (i==s) & (j!=t):
                        inner += np.exp(-(tensor[i,j,0]-tensor[s,t,0])**2)
                        n_inner += 1
                    # between clusters
                    if i!=s:
                        outer += np.exp(-(tensor[i,j,0]-tensor[s,t,0])**2)
                        n_outer += 1
    # avg within clusters minus avg between clusters
    return (inner / n_inner) - (outer / n_outer)

def unit_test_cov(tensor1, tensor2):
    assert tensor1.shape == tensor2.shape
    n, m, _ = tensor1.shape
    n_inner = 0
    n_outer = 0
    inner = 0
    outer = 0
    for i in range(n):
        for j in range(m):
            for s in range(n):
                for t in range(m):
                    # within clusters
                    if i==s:
                        inner += np.exp(-(tensor1[i,j,0]-tensor2[s,t,0])**2)
                        n_inner += 1
                    # between clusters
                    if i!=s:
                        outer += np.exp(-(tensor1[i,j,0]-tensor2[s,t,0])**2)
                        n_outer += 1
    # avg within clusters minus avg between clusters
    return (inner / n_inner) - (outer / n_outer)

In [4]:
t3 = np.arange(0, 4).reshape(2, 2, 1)
t4 = np.arange(5, 9).reshape(2, 2, 1)
print(t3)
print(t3.shape)

[[[0]
  [1]]

 [[2]
  [3]]]
(2, 2, 1)


In [5]:
print(unit_test_var(t3))
print(unit_test_cov(t3, t4))

0.266720908983193
-0.0023202932382726015


In [6]:
print(dist_var(t3))
print(dist_cov(t3, t4))

0.266720908983193
-0.002320293238272602


In [7]:
print(dist_var_(t3))
print(dist_cov_(t3, t4))

0.266720908983193
-0.0023202932382726015


In [8]:
t3 = np.arange(0, 12).reshape(4, 3, 1)
t4 = np.arange(12, 24).reshape(4, 3, 1)
print(t3)
print(t3.shape)

[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]]
(4, 3, 1)


In [9]:
print(unit_test_var(t3))
print(unit_test_cov(t3, t4))

0.2288647710501299
-0.0037489018386232475


In [10]:
print(dist_var(t3))
print(dist_cov(t3, t4))

0.2288647710501299
-0.0037489018386232475


In [11]:
print(dist_var_(t3))
print(dist_cov_(t3, t4))

0.2288647710501299
-0.003748901838623247


In [12]:
### RUNTIME COMPARISON

In [13]:
# ~22s
%%time
rng = np.random.default_rng(0)
for _ in range(100):
    t3 = rng.random(400).reshape(20, 20, 1)
    t4 = rng.random(400).reshape(20, 20, 1)

    _ = unit_test_var(t3)
    _ = unit_test_cov(t3, t4)

CPU times: user 22.2 s, sys: 58.6 ms, total: 22.2 s
Wall time: 22.3 s


In [14]:
# ~0.23s
%%time
rng = np.random.default_rng(0)
for _ in range(100):
    t3 = rng.random(400).reshape(20, 20, 1)
    t4 = rng.random(400).reshape(20, 20, 1)

    _ = dist_var_(t3)
    _ = dist_cov_(t3, t4)

CPU times: user 227 ms, sys: 4.47 ms, total: 231 ms
Wall time: 231 ms


In [15]:
# ~0.19s
%%time
rng = np.random.default_rng(0)
for _ in range(100):
    t3 = rng.random(400).reshape(20, 20, 1)
    t4 = rng.random(400).reshape(20, 20, 1)

    _ = dist_var(t3)
    _ = dist_cov(t3, t4)

CPU times: user 185 ms, sys: 5.09 ms, total: 190 ms
Wall time: 189 ms
